on:
  push:
  workflow_dispatch:

name: render sofunCalVal repo

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/computationales/sofunCalVal/dispatches \
              --raw-field event_type=render
